### ISSUE TITLE
Release for darwin_arm64

### ISSUE THREAD

**Issue by wilfriedroset** [camptocamp/terraform-provider-puppetca#13]
The latest version does not come with a release for `darwin_arm64` which makes the provider unusable on macbook with M1 processor

```
╷
│ Error: Could not retrieve providers for locking
│
│ Terraform failed to fetch the requested providers for darwin_arm64 in order to calculate their checksums: some providers could not be installed:
│ - registry.terraform.io/camptocamp/puppetca: provider registry.terraform.io/camptocamp/puppetca 1.4.0 is not available for darwin_arm64.
╵
```

Could you please include this platform in the release plan?

**Comment by tnorris** [comment]
I am not a maintainer of this project, but I was able to get a darwin_arm64 artifact by running

```
$ goreleaser --skip-validate --skip-publish --rm-dist --skip-sign
```

in the repo root.

**Comment by wilfriedroset** [comment]
Indeed this workaround is the way to go when you work on an instance when you can define your own `~/.terraformrc`
Something like
```
plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"
provider_installation {

  dev_overrides {
    "camptocamp/puppetca" = "/home/wilfried/workspace/github.com/camptocamp/terraform-provider-puppetca"
  }
}
```

This is not applicable when you use terraform cloud or terraform enterprise.

**Comment by yann-soubeyrand** [comment]
Better late than never, v2.0.0 comes with a Darwin ARM64 build.
