### ISSUE TITLE
Need Example

### ISSUE THREAD

**Issue by cospeedster** [camptocamp/terraform-provider-puppetca#3]
Hello,

can you provide an example how to use this provider?

The following doesn't work for me:

```HCL
provider "puppetca" {
    url = "puppetca.example.com"
}

resource "puppetca_certificate" "cert" {
    name = "testcert.example.com"
}
```

Terraform plan output:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: failed to load client cert from string: tls: failed to find any PEM data in certificate input

  on main.tf line 1, in provider "puppetca":
   1: provider "puppetca" {

```

I want to get a client certificate for a new host.

**Comment by mcanevet** [comment]
`Error: failed to load client cert from string: tls: failed to find any PEM data in certificate input` means you forgot to provide a client cert to the provider's configuration.

**Comment by cospeedster** [comment]
So I have to create a client cert to use this provider?

Can you provide an example how to use this provider?

**Comment by raphink** [comment]
I just updated the README with an example: https://github.com/camptocamp/terraform-provider-puppetca/blob/master/README.md
