### ISSUE TITLE
Documentation: Format for Certificates

### ISSUE THREAD

**Issue by whoracle** [camptocamp/terraform-provider-puppetca#6]
I tried using this provider and am seemingly unable to pass the cert data to the provider. The code in go-puppetca api client suggests that I need to pass the PEM payload instead of a path - is that correct? I tried it with e.g.

```
provider puppetca {
  url = "https://puppetca.example.com:8140"
  cert = trimspace(<<-EOT
      -----BEGIN CERTIFICATE-----
      BLABLALBLA
      -----END CERTIFICATE-----
    EOT
    )
   [... etc ...]
}
```

and am getting

```
Error: failed to load client cert from string: tls: failed to find any PEM data in certificate input
```

from terraform.

Any pointers?

**Comment by whoracle** [comment]
It's been quite a while, so: Any takers?

**Comment by poulpreben** [comment]
The `cert`, `key` and `ca` variables should be full paths to the certificates of a client which is authorized to perform write operations on the Puppet CA. It does not work if you pass them in PEM format.

**Comment by yann-soubeyrand** [comment]
Hello, it should be possible to passe either a path to a PEM file or directly the PEM content. There’s one restriction however: private key and certificate must be passed the same way.
