### ISSUE TITLE
ec2 instance replacement does not trigger a clean of the cert

### ISSUE THREAD

**Issue by iarjune** [camptocamp/terraform-provider-puppetca#7]
The Hashicorp aws provisioner will replace an ec2 instance, instead of destroying it, for things like an ami change.

For example

`# module.stage-test-01.module.ec2_instance.aws_instance.this[0] must be replaced
-/+ resource "aws_instance" "this" {
      ~ ami                                  = "ami-0e5af4c8f51e85fcf" -> "ami-0f51a91f5a5d2d99b" # forces replacement`

This  provider, terraform-provider-puppetca, does not clean the cert when the instance is replaced.  Cleaning the cert on a destroy operation works as expected, but not when the instance is being replace.

This has been tested with 
registry.terraform.io/hashicorp/aws/3.56.0 
registry.terraform.io/camptocamp/puppetca/1.3.0

**Comment by yann-soubeyrand** [comment]
Hello, sorry for the very late reply, but doesn’t the `usedby` argument make what you’re looking for?
